### ISSUE TITLE
Docker compose use

### ISSUE THREAD

**Issue by Buongiordanno** [progrium/docker-stress#2]
Hi, how do i pass args (e.g. --cpu 2 --io 1) in a docker-compose.yml ?

version: '2'
services:
  app01:
    image: progrium/stress
      cpu: 2
      io: 1
      vm: 2
      vm-bytes: 128M
      timeout: 10s

this is what i've done, but it doesnt work, help me please.

**Comment by JoshKeegan** [comment]
I think you could use `command`: https://docs.docker.com/compose/compose-file/#command
Although you may have to also pass the entrypoint, e.gL
```yaml
services:
  foo:
    command: /usr/bin/stress --verbose --cpu 2
```
I haven't tried this though :)
